# Generated by Django 3.2.12 on 2022-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='cud_current_treatment_phase',
            field=models.CharField(choices=[('PROGRESSION', 'Progression'), ('FOLLOWUP', 'Follow-up'), ('PRIMARYCHEMO', 'Primary chemotherapy'), ('DRUGTRIAL', 'Drug trial'), ('HORMONAL', 'Hormonal treatment')], max_length=20),
        ),
    ]
