# Generated by Django 3.2.15 on 2022-09-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='time_series',
            field=models.CharField(blank=True, max_length=5100, null=True),
        ),
    ]
