# Generated by Django 3.2.16 on 2022-10-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0003_merge_20221014_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='event_series',
            field=models.CharField(blank=True, max_length=5100, null=True),
        ),
    ]
