# Generated by Django 3.2.16 on 2022-11-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0004_clinicaldata_event_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
