# Generated by Django 3.2.16 on 2022-11-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0006_clinicaldata_sequencing_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='sequencing_available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
