# Generated by Django 3.2.16 on 2022-11-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0007_alter_clinicaldata_sequencing_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='age',
            new_name='age_at_diagnosis',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='height',
            new_name='height_at_diagnosis',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='weight',
            new_name='weight_at_diagnosis',
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='paired_fresh_samples_available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='wgs_available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
