# Generated by Django 3.2.16 on 2022-11-03 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0008_auto_20221103_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='height_at_diagnosis',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(300.0)]),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='weight_at_diagnosis',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
    ]
