# Generated by Django 3.2.16 on 2022-11-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0010_auto_20221103_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaldata',
            name='chronic_illnesses',
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='chronic_illnesses_at_dg',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='treatment_strategy',
            field=models.CharField(choices=[('NACT', 'Neo-adjuvant chemotherapy'), ('PDS', 'Primary debulking surgery'), ('Other', 'Other')], max_length=20),
        ),
    ]
