# Generated by Django 3.2.16 on 2022-11-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0017_auto_20221103_1218'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='progression-constraint1',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='outcome-constraint1',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='outcome-constraint2',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='has_wgs',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='progression_date',
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='days_from_beva_maintenance_end_to_progression',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='days_to_death',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='days_to_progression',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='operation1_cancelled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='platinum_free_interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='residual_tumor_pds',
            field=models.CharField(choices=[('ZERO', '0'), ('ZEROTEN', '1 to 10mm'), ('OVERTEN', 'more than 10mm')], max_length=100, null=True),
        ),
    ]
