# Generated by Django 3.2.16 on 2022-11-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0018_auto_20221103_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaldata',
            name='has_brca_mutation',
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='brca_mutation_status',
            field=models.CharField(choices=[('NOBRCA', 'No BRCA mut'), ('BRCA1TUMOR', 'BRCA1 in tumor'), ('BRCA1BLOOD', 'BRCA1 in blood'), ('BRCA2TUMOR', 'BRCA2 in tumor'), ('BRCA2BLOOD', 'BRCA2 in blood')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='debulking_surgery_ids',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='operation2_cancelled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='residual_tumor_ids',
            field=models.CharField(choices=[('ZERO', '0'), ('ZEROTEN', '1 to 10mm'), ('OVERTEN', 'more than 10mm')], max_length=100, null=True),
        ),
    ]
