# Generated by Django 3.2.16 on 2022-11-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0019_auto_20221103_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaldata',
            name='has_hrd',
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='hr_signature_pretreatment_wgs',
            field=models.CharField(choices=[('HRD', 'HRD'), ('HRP', 'HRP')], max_length=100, null=True),
        ),
    ]
