# Generated by Django 3.2.16 on 2022-11-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0022_clinicaldata_hrd_myriad_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='operation-constraint2',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='followup-constraint1',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='followup-constraint2',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='lapra-constraint1',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='diagnosis-constraint1',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='operation-constraint1',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='maintenance-constraint1',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='date_of_outcome',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='last_followup_visit',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='last_primary_chemo',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='maintenance_therapy_end',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='nact_cycles',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='next_followup_visit',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='post_ids_cycles',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='primary_chemo_cycles',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='primary_laprascopy_date',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='primary_operation_date',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='progression_detection_method',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='response_ct_date',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='secondary_operation_date',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='stage_info',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='time_of_diagnosis',
        ),
    ]
