# Generated by Django 3.2.16 on 2022-11-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0024_auto_20221103_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='patient_id',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
