# Generated by Django 3.2.16 on 2022-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0026_alter_clinicaldata_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='sequencing_available',
            field=models.BooleanField(default=False),
        ),
    ]
