# Generated by Django 3.2.16 on 2022-11-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0027_alter_clinicaldata_sequencing_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='paired_fresh_samples_available',
            field=models.BooleanField(default=False),
        ),
    ]
