# Generated by Django 3.2.12 on 2022-04-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('description_url', models.TextField(blank=True, null=True)),
                ('cid', models.CharField(max_length=9)),
                ('molecular_formula', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.CharField(max_length=7)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs_a', to='side_effects.drug')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs_b', to='side_effects.drug')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='side_effects.effect')),
            ],
        ),
        migrations.AddConstraint(
            model_name='effect',
            constraint=models.UniqueConstraint(fields=('cui',), name='unique_cui'),
        ),
        migrations.AddField(
            model_name='drug',
            name='effects',
            field=models.ManyToManyField(to='side_effects.Effect'),
        ),
        migrations.AddField(
            model_name='drug',
            name='interactions',
            field=models.ManyToManyField(blank=True, through='side_effects.Interaction', to='side_effects.Drug'),
        ),
        migrations.AddConstraint(
            model_name='drug',
            constraint=models.UniqueConstraint(fields=('cid',), name='unique_cid'),
        ),
    ]
