# Generated by Django 3.2.16 on 2022-10-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0002_alter_clinicaldata_cud_current_treatment_phase'),
        ('clin_overview', '0002_clinicaldata_time_series'),
    ]

    operations = [
    ]
