# Generated by Django 3.2.16 on 2022-11-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0005_rename_patient_clinicaldata_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='sequencing_available',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
