# Generated by Django 3.2.16 on 2022-11-03 10:51

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0009_auto_20221103_1144'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='lapra-constraint1',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='diagnosis-constraint1',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='operation-constraint1',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='maintenance-constraint1',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='progression-constraint1',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='outcome-constraint1',
        ),
        migrations.RemoveConstraint(
            model_name='clinicaldata',
            name='outcome-constraint2',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='cud_current_treatment_phase',
            new_name='current_treatment_phase',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='cud_date_of_death',
            new_name='date_of_death',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='cud_date_of_outcome',
            new_name='date_of_outcome',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='cud_histology',
            new_name='histology',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='cud_last_primary_chemo',
            new_name='last_primary_chemo',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='cud_primary_therapy_outcome',
            new_name='primary_therapy_outcome',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='cud_progression_date',
            new_name='progression_date',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='cud_stage',
            new_name='stage',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='cud_stage_info',
            new_name='stage_info',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='cud_survival',
            new_name='survival',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='cud_time_of_diagnosis',
            new_name='time_of_diagnosis',
        ),
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='cud_treatment_strategy',
            new_name='treatment_strategy',
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='bmi_at_diagnosis',
            field=models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='clinicaldata',
            constraint=models.CheckConstraint(check=models.Q(('primary_laprascopy_date__lt', django.db.models.expressions.F('time_of_diagnosis'))), name='lapra-constraint1'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldata',
            constraint=models.CheckConstraint(check=models.Q(('time_of_diagnosis__lt', django.db.models.expressions.F('primary_operation_date'))), name='diagnosis-constraint1'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldata',
            constraint=models.CheckConstraint(check=models.Q(('primary_operation_date__lt', django.db.models.expressions.F('last_primary_chemo'))), name='operation-constraint1'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldata',
            constraint=models.CheckConstraint(check=models.Q(('last_primary_chemo__lt', django.db.models.expressions.F('maintenance_therapy_end'))), name='maintenance-constraint1'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldata',
            constraint=models.CheckConstraint(check=models.Q(('maintenance_therapy_end__lt', django.db.models.expressions.F('progression_date'))), name='progression-constraint1'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldata',
            constraint=models.CheckConstraint(check=models.Q(('progression_date__lt', django.db.models.expressions.F('date_of_death'))), name='outcome-constraint1'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldata',
            constraint=models.CheckConstraint(check=models.Q(('date_of_outcome__lt', django.db.models.expressions.F('date_of_death'))), name='outcome-constraint2'),
        ),
    ]
