# Generated by Django 3.2.16 on 2022-11-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0012_clinicaldata_chronic_illnesses_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='previous_cancer',
            field=models.BooleanField(null=True),
        ),
    ]
