# Generated by Django 3.2.16 on 2022-11-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0013_clinicaldata_previous_cancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='previous_cancer_diagnosis',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='survival',
            field=models.CharField(choices=[('DEATHUNKNOWN', 'Death due to unknown reason'), ('DEATHOTHER', 'Death due to other reason'), ('DEATHCANCER', 'Death due to cancer'), ('ALIVE', 'Alive')], max_length=20),
        ),
    ]
