# Generated by Django 3.2.16 on 2022-11-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0015_clinicaldata_progression'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='followup_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='primary_therapy_outcome',
            field=models.CharField(choices=[('PARTIAL', 'Partial response'), ('COMPLETE', 'Complete response'), ('PROGRESSIVE', 'Progressive disease'), ('DEATH', 'Died during chemotherapy'), ('PROGRESSIVENACT', 'Progressive disease after nact'), ('SIDEEFFECTSTOP', 'Stopped due to side effects'), ('STABLENACT', 'Stable disease after nact'), ('NOCHEMO', 'No chemotherapy'), ('STABLE', 'Stable disease')], max_length=20),
        ),
    ]
