# Generated by Django 3.2.16 on 2022-11-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clin_overview', '0030_alter_clinicaldata_primary_therapy_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='stage',
            field=models.CharField(choices=[('IA', 'Ia'), ('IB', 'Ib'), ('IC1', 'Ic1'), ('IC2', 'Ic2'), ('IC3', 'Ic3'), ('IIA', 'Iia'), ('IIB', 'Iib'), ('IIIA1i', 'Iiia1I'), ('IIIA1ii', 'Iiia1Ii'), ('IIIA2', 'Iiia2'), ('IIIB', 'Iiib'), ('IIIC', 'Iiic'), ('IVA', 'Iva'), ('IVB', 'Ivb')], max_length=20, null=True),
        ),
    ]
